core: 7.x
api: 2
projects:
  - drupal
  - ctools:
   		subdir: 'contrib'
  - deploy:
   		subdir: 'contrib'
  - devel:
   		subdir: 'contrib'
  - entity:
   		subdir: 'contrib'
  - entity_dependency:
   		subdir: 'contrib'
  - entity_menu_links:
   		subdir: 'contrib'
  - fieldable_panels_panes:
   		subdir: 'contrib'
  - file_entity:
   		subdir: 'contrib'
  - libraries:
   		subdir: 'contrib'
  - panels:
   		subdir: 'contrib'
  - services:
   		subdir: 'contrib'
  - services_entity:
   		subdir: 'contrib'
  - taxonomy_revision:
   		subdir: 'contrib'
  - uuid:
   		subdir: 'contrib'
  - views:
   		subdir: 'contrib'
